"""empty message

Revision ID: c0fc5c37c965
Revises: f93b4448abbb
Create Date: 2022-05-27 21:40:38.503582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fc5c37c965'
down_revision = 'f93b4448abbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('URL_map_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('custom_id', sa.String(length=6), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_id')
    )
    op.create_index(op.f('ix_URL_map_api_timestamp'), 'URL_map_api', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_URL_map_api_timestamp'), table_name='URL_map_api')
    op.drop_table('URL_map_api')
    # ### end Alembic commands ###
